version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    volumes:
      - redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: --databases 100
    ports:
      - "6379:6379"
    tty: true
    healthcheck:
      test: redis-cli ping
      interval: 300s
      timeout: 10s

  rails-app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: rails-app
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    links:
      - postgres:db
      - redis:redis

volumes:
  db-postgres: {}
  redis:
