version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_rails
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-postgres:/var/lib/postgresql/data

  rails-app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: rails-app
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    links:
      - postgres:db

volumes:
  db-postgres: {}
