FROM ruby:3.3.0-alpine

WORKDIR /app

RUN apk update && apk add --no-cache build-base postgresql-dev tzdata

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install --without test

COPY . .

EXPOSE 3000

RUN rm -f tmp/pids/server.pid

CMD ["rails", "server", "-b", "0.0.0.0"]
