FROM ruby:3.3.0

RUN apt update && \
    apt install -y \
    build-essential patch ruby-dev tzdata \
    libpq-dev postgresql-contrib vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

RUN rm -f ./tmp/pids/server.pid

CMD ["rails", "server", "-b", "0.0.0.0"]
