FROM ruby:3.3.0


RUN apt update -qq && \
    apt install -y \
    build-essential patch ruby-dev tzdata\
    libpq-dev postgresql-contrib vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

COPY Gemfile* ./

RUN gem install bundler && bundle install

RUN gem install foreman

COPY . /app

EXPOSE 3000

CMD bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
