default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  statement_timeout: 200
  # host: localhost
  # usename: aliriods
  # password: postgres
  # database: bd_template_dev
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'rails_boiler_plate_development') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'rails_boiler_plate_test') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>

production:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'rails_boiler_plate_production') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
